demo/time-picker-basic-demos.html
src/vaadin-time-picker.html
test/input-test.html
test/step-test.html
test/test-suites.js

Fixes #4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-time-picker/14)

Step property

---

.travis.yml
bower.json
src/vaadin-time-picker.html
test/dropdown-test.html
test/test-suites.js
theme/lumo/vaadin-time-picker-styles.html

Fixes #5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-time-picker/15)

Add dropdown

---

demo/time-picker-basic-demos.html
src/vaadin-time-picker.html
test/dropdown-test.html
test/input-test.html
test/step-test.html

Fixes #6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-time-picker/17)

Consider steps in dropdown items list.

---

src/vaadin-time-picker.html
test/input-test.html

Fixes #21
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-time-picker/22)

Fix regexp

---

analysis.json
demo/time-picker-basic-demos.html
src/vaadin-time-picker.html
test/custom-functions.html
test/dropdown-test.html
test/input-test.html
test/test-suites.js

Fixes #7
Should be merged after #6 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-time-picker/16)

Custom parser and formatter

---

src/vaadin-time-picker.html
test/custom-functions.html
test/input-test.html

Fix #23
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-time-picker/25)

Change event

---

analysis.json
bower.json
src/vaadin-time-picker.html
test/input-test.html

Fixes #10
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-time-picker/27)

Align props and mixin with other elements. Implement readonly/disabled.

---

bower.json
demo/time-picker-advanced-demos.html
src/vaadin-time-picker.html
test/custom-functions.html
test/form-input.html
test/input-test.html
test/test-suites.js

Connected to #11
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-time-picker/26)

Support iron-form

---

src/vaadin-time-picker.html
test/input-test.html

Fixes #9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-time-picker/31)

Add a11y attributes

---

.eslintrc.json
bower.json
demo/time-picker-basic-demos.html
src/vaadin-time-picker.html
test/dropdown-test.html
test/keyboard-navigation.html
test/test-suites.js

Fixes #12
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-time-picker/29)

Keyboard navigation

---

demo/time-picker-advanced-demos.html
demo/time-picker-basic-demos.html
src/vaadin-time-picker.html
test/input-test.html
test/keyboard-navigation.html

Fixes #32 #37 #44 #45
Connects to #32
Connects to #37 
Connects to #44
Connects to #45
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-time-picker/54)

Fixes to UX findings

---

src/vaadin-time-picker.html
test/keyboard-navigation.html

Fixes #46
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-time-picker/56)

Fix arrow key when overlay

---

bower.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-time-picker/59)

Do not depend on p3-preview

---

theme/material/vaadin-time-picker-styles.html
theme/material/vaadin-time-picker.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-time-picker/60)

Adding material entry points

---

.travis.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-time-picker/61)

Align travis file with the rest of elements

---

src/vaadin-time-picker.html
test/keyboard-navigation.html

Fixes #36
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-time-picker/38)

Add __memoValue to work within keyboard navigation

---

src/vaadin-time-picker.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-time-picker/67)

Typo in the javadoc

---

src/vaadin-time-picker.html
test/input-test.html
test/keyboard-navigation.html
test/step-test.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-time-picker/68)

Increase coverage

---

bower.json
demo/demos.json
demo/index.html
demo/time-picker-styling-demos.html
src/vaadin-time-picker.html
test/styling.html
test/test-suites.js

Connected to vaadin/vaadin-themable-mixin#12
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-time-picker/74)

Propagate theme attribute to internal components

---

bower.json
demo/time-picker-advanced-demos.html
demo/time-picker-basic-demos.html

Connected to vaadin/components-team-tasks#389
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-time-picker/76)

Ignore ES6 demo in IE11, move custom formatter demo [skip ci]

---

demo/time-picker-advanced-demos.html

Fixes #77
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-time-picker/78)

Fix time values in custom formatter demo

---

demo/time-picker-advanced-demos.html

Fixes #77
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-time-picker/82)

Fix time values in custom formatter demo [skip ci]

---

src/vaadin-time-picker.html
test/input-test.html

Fixes #83
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-time-picker/85)

Add intuitive milliseconds autocompletion

---

src/vaadin-time-picker.html
test/custom-functions.html

Fixes #80
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-time-picker/86)

Update dropdown value on i18n reassigning

---

src/vaadin-time-picker.html
test/input-test.html

Fixes #88
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-time-picker/89)

Restore the previous value in input field if input value is empty

---

demo/time-picker-basic-demos.html
src/vaadin-time-picker.html
test/range-test.html
test/test-suites.js

Fixes #47.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-time-picker/92)

Set minimum and maximum time range

---

demo/time-picker-basic-demos.html
src/vaadin-time-picker.html
test/range-test.html
test/test-suites.js

Fixes #47 
Closes #93
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-time-picker/94)

Add min and max properties

---

src/vaadin-time-picker.html
test/input-test.html

Fixes #91 
Visual tests are failing on master as well
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-time-picker/95)

Clear value with null

---

README.md

fixes #98
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-time-picker/103)

Align README to skeleton

---

src/vaadin-time-picker.html
test/custom-functions.html
test/input-test.html

Fixes #97
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-time-picker/104)

Set value to empty string when input value is invalid

---

bower.json
demo/time-picker-basic-demos.html
src/vaadin-time-picker.html
test/input-test.html

Fixes #105
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-time-picker/107)

feat: add clear-button-visible API from <vaadin-text-field>

---

bower.json
src/vaadin-time-picker.html
test/input-test.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-time-picker/108)

feat(i18n): add support for clear button accessible label

---

src/vaadin-time-picker.html
test/input-test.html

Fixes #109
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-time-picker/110)

fix: add missing change event

---

src/vaadin-time-picker.html

fix: make it possible to override query selector for the input element

---

src/vaadin-time-picker.html
test/range-test.html

Don't change value on setting min/max if empty

---

src/vaadin-time-picker.html
test/form-input.html

Connected to https://github.com/vaadin/vaadin-date-time-picker/issues/17

Update validation timing, add validation on blur

---

demo/time-picker-advanced-demos.html

Fix https://github.com/vaadin/90min-dx-tasks/issues/111
Fixes #100

Fix parseTime in Custom Parser and Formatter demo [skip ci]

---

demo/index.html
demo/time-picker-basic-demos.html

Fixes: https://github.com/vaadin/vaadin-time-picker/issues/49 https://github.com/vaadin/90min-dx-tasks/issues/114

Improve step example

---

src/vaadin-time-picker.html
test/input-test.html

Fix: read-only styles missing when in read only mode

---

bower.json
src/vaadin-time-picker.html
test/dropdown-test.html

Fixes #136 
Needs vaadin/vaadin-combo-box#853 to be merged and released to pass.

Add autoOpenDisabled property

---

bower.json
demo/time-picker-basic-demos.html
src/vaadin-time-picker.html
test/dropdown-test.html

feat: add autoOpenDisabled property

---

src/vaadin-time-picker.html

docs: add JSDoc for attributes [skip ci] (#155)

---

demo/time-picker-advanced-demos.html

Fixes https://github.com/vaadin/vaadin-time-picker/issues/147

Fix NPE in Custom Validator demo

---

demo/time-picker-advanced-demos.html

Cherry-pick to `2.2` branch for V14.3

docs: fix custom validator demo [skip ci] (#154)

---

src/vaadin-time-picker.html
test/validation.html

Backports the following PRs:
- https://github.com/vaadin/web-components/pull/4084
Part of https://github.com/vaadin/web-components/issues/5763

feat: fire a validated event on validation (CP: 14)

---

src/vaadin-time-picker.html
test/validation.html

Backports the following PRs:
- https://github.com/vaadin/web-components/pull/4097
Part of https://github.com/vaadin/web-components/issues/5763

feat: add methods to make setting invalid overridable (CP: 14)

---

src/vaadin-time-picker.html

This PR adds the JSDoc for the validate method that was updated
Part of https://github.com/vaadin/vaadin-time-picker/pull/206
Part of https://github.com/vaadin/web-components/issues/5763

docs: add JSDoc for validate method (CP: 14)

---

bower.json
package-lock-p3.json

Updated the dependency version.
- Version bump

chore: update vaadin-combo-box to 5.5.2
